# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 61d67410a47458cb01e103ba43c3233188d1b59f5b4539ddb61169b4854406225fdd9770ba913ea1e25fa40134f45ac3a177524711aeb8906a6f4d6c26f47a0c

test:
  secret_key_base: 1e8a843ea182ac98f6cc845e68368a13285d25a55f90aae23325d0328c7935b14017640ff714890586f8bdf35ca347e6776fb11b89ecf4eec7449e99af27cd85

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
